#:schema node_modules/wrangler/config-schema.json

name = "test-better-auth"
pages_build_output_dir = "./dist"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]
# main = "./worker/index.ts"

[observability]
enabled = true

# [assets]
# not_found_handling = "single-page-application"
# run_worker_first = ["/api/*"]
