#:schema node_modules/wrangler/config-schema.json

name = "test-better-auth"
compatibility_date = "2025-03-05"
compatibility_flags = ["nodejs_compat"]
assets = { not_found_handling = "single-page-application" }

[observability]
enabled = true
