#:schema node_modules/wrangler/config-schema.json

name = "test-better-auth-worker"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]
main = "./functions/index.ts"

[observability]
enabled = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
